const topics = [
  "Your biggest concern for the future.",
  "Real wealth isn't measured in money.",
  "If I were an animal, I would be...",
  "What real love is.",
  "Plants have feelings too.",
  "Junk food's popularity relies on marketing.",
  "When I grow up...",
  "Growing up is a state of mind.",
  "Why goals are good for you.",
  "Why intelligence isn't enough.",
  "The most important lesson that I've learned is...",
  "If I ruled the world...",
  "Why colours can change the way you feel.",
  "Team sports build strong individuals.",
  "Laughter is the best medicine.",
  "Why discipline is good.",
  "Beauty is in the eye of the beholder.",
  "Children learn what they live with.",
  "Poverty is a state of mind.",
  "What characteristics make an ideal hero.",
  "What and who is an average person.",
  "Being young is over-rated.",
  "When is lying a good idea?",
  "Does money make the world go round?",
  "What human quality is under-rated?",
  "Who is the most influential person in your life?",
  "Pets are for people that don't have children.",
  "Summer is the best and worst season.",
  "Advertising to children is immoral.",
  "The media controls how we think.",
  "Talking to someone and talking with someone are different.",
  "Real learning doesn't occur in a classroom.",
  "Being wise vs. being intelligent.",
  "True wisdom comes from experience.",
  "Why a good sense of humour is essential.",
  "Uniforms stifle individuality.",
  "What is considered normal is determined by society.",
  "Manners matter.",
  "Children should not watch television.",
  "Art is essential to life.",
  "True peace is possible.",
  "Non-bias news is impossible.",
  "Performance enhancing drugs should be allowed in professional sports.",
  "Poor health begins in the mind.",
  "What characteristics define a good villain?",
  "Being influential is better than being rich.",
  "Violent video games make you violent.",
  "Climate change is natural.",
  "Space exploration advances the human race.",
  "Parents are the most influential factors in our lives.",
  "Athlete salaries are justified by the views they receive.",
  "Reading fiction is a waste of time.",
  "Going to university/college isn't necessary.",
  "Social media makes society less happy.",
  "Anyone can become a millionaire with enough hard work.",
  "Translation technology will replace the need to learn a new language.",
  "Colonizing Mars is a necessity.",
  "Being vegetarian is healthier than eating meat.",
  "Is sexual orientation determined at birth?",
  "A higher power exists."
]

getTopic = () => {
  let r = Math.floor(Math.random() * 60);
  let selectedTopic = topics[r];
  document.getElementById("topic").innerHTML = selectedTopic;
}
